In [1]:
# import needed libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls
import plotly.graph_objs as go
tls.set_credentials_file(username='softdesinfinity2', api_key='rVvqvP7LcJ9vC1WAixOv')
# tls.set_credentials_file(username='enter info', api_key='enter info')

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__)
init_notebook_mode(connected=True)

2.6.0


In [3]:
# libraries for PCoA
from scipy.spatial import distance
# skbio's PCoA library used for verification
from skbio.stats.ordination import pcoa
from skbio.diversity import beta_diversity

ModuleNotFoundError: No module named 'skbio'

In [4]:
#Create a DataFrame containing the data you wish to analyze.
#In this case it is the GH metagenomics data
df = pd.read_csv(
    filepath_or_buffer='meta_data.csv', 
    header=None, 
    sep=',')
df

0   1   2   3    4   5   6   7    8   9  ...   11  12   13  14  15   16  \
0   26  21  24  28   52  19  39  13   20  12 ...    4  14   27  37   6  365   
1   67  44  55  62  103  36  68  51  127  54 ...    6  80  115  81  19  476   
2   42  50  58  64   65  12  41  55   74  23 ...    5  53  103  27   3  169   
3   21  26  21  25   31  12  23  27   45  18 ...    0  26   54  12   0   95   
4    7   4   5   4   10   1   9  10    4   1 ...    0   2    7   3   0    0   
5    0   0   0   0    0   1   0   0    0   0 ...    0   0    2   0   0    0   
6   20  14  20  22   27  14  13  19   36  12 ...    0  27   37  21   4  128   
7    2   1   3   0    1   2   1   2    4   7 ...    0  11    7  10   0   50   
8    6   4   8   7    8   1   6  10    5   7 ...    0   4    6   7   0   15   
9   77  59  64  84  128  26  65  80   91  53 ...    4  79  112  60   4  239   
10   5   4   3   5    8   2   5   6    6   5 ...    0   4    5   5   0   21   
11  34  17  28  29   45   2  29  27   35  15 ...    1  35   47  17   9  241   
12  37  33  37  52   70  15  46  33   60  44 ...    5  26   41  69  15  428   
13  63  45  55  42  109  15  63  49   76  28 ...    1  53  110  48   4  253   
14  10  21  24  20   30   6  12  29   21   5 ...    1  21   39   3   0   47   
15  21  21  14  33   39  12  26  21   54  14 ...    1  21   39  27   0  129   
16  34  18  18  16   55   5  40  31   23  14 ...    0  15   39  30   1  180   

     17   18   19   20  
0    93  113  222  272  
1   348  560  252  320  
2    57   75   64  102  
3    10    4   22   36  
4     0    0    0   18  
5     0    0    0    0  
6    17   21   29   45  
7     0    0    0    0  
8    22   13    6   20  
9    33  118   35   70  
10    9   10    1    4  
11  185  181  118   45  
12   73   98   59  198  
13   50   58   84   85  
14    1    2    2   22  
15   35   24    0    0  
16   17   27   44   41  

[17 rows x 21 columns]

In [5]:
#Show another way to get a Numpy representation of a Dataframe
D = df.ix[:,0:21].values
print(D)

[[ 26  21  24  28  52  19  39  13  20  12  20   4  14  27  37   6 365  93
  113 222 272]
 [ 67  44  55  62 103  36  68  51 127  54  63   6  80 115  81  19 476 348
  560 252 320]
 [ 42  50  58  64  65  12  41  55  74  23  48   5  53 103  27   3 169  57
   75  64 102]
 [ 21  26  21  25  31  12  23  27  45  18  38   0  26  54  12   0  95  10
    4  22  36]
 [  7   4   5   4  10   1   9  10   4   1   4   0   2   7   3   0   0   0
    0   0  18]
 [  0   0   0   0   0   1   0   0   0   0   0   0   0   2   0   0   0   0
    0   0   0]
 [ 20  14  20  22  27  14  13  19  36  12  31   0  27  37  21   4 128  17
   21  29  45]
 [  2   1   3   0   1   2   1   2   4   7  11   0  11   7  10   0  50   0
    0   0   0]
 [  6   4   8   7   8   1   6  10   5   7   4   0   4   6   7   0  15  22
   13   6  20]
 [ 77  59  64  84 128  26  65  80  91  53  48   4  79 112  60   4 239  33
  118  35  70]
 [  5   4   3   5   8   2   5   6   6   5   7   0   4   5   5   0  21   9
   10   1   4]
 [ 34  17  28  29  45

C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:


.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated



In [6]:
# Compute the Bray-curtis distance between all combinations of sample pairs and place values into a distance matrix
# The diagonal values will all be 0 because a variable is no distance away from itself
B = []
for row in D:
    B_row = []
    for row2 in D:
        B_row.append(distance.braycurtis(row, row2))
    B.append(B_row)
B = np.matrix(B)
B.round(2).reshape(17, 17)

array([[ 0.  ,  0.35,  0.38,  0.55,  0.88,  1.  ,  0.49,  0.85,  0.8 ,
         0.42,  0.85,  0.3 ,  0.21,  0.36,  0.67,  0.51,  0.41],
       [ 0.35,  0.  ,  0.44,  0.69,  0.94,  1.  ,  0.69,  0.93,  0.9 ,
         0.37,  0.93,  0.44,  0.34,  0.39,  0.8 ,  0.69,  0.63],
       [ 0.38,  0.44,  0.  ,  0.37,  0.86,  0.99,  0.37,  0.83,  0.76,
         0.19,  0.82,  0.32,  0.25,  0.13,  0.57,  0.36,  0.29],
       [ 0.55,  0.69,  0.37,  0.  ,  0.72,  0.99,  0.15,  0.66,  0.61,
         0.47,  0.67,  0.43,  0.47,  0.42,  0.26,  0.21,  0.25],
       [ 0.88,  0.94,  0.86,  0.72,  0.  ,  0.93,  0.72,  0.68,  0.34,
         0.89,  0.42,  0.86,  0.89,  0.87,  0.58,  0.78,  0.77],
       [ 1.  ,  1.  ,  0.99,  0.99,  0.93,  0.  ,  0.99,  0.95,  0.96,
         1.  ,  0.95,  0.99,  1.  ,  1.  ,  0.98,  0.99,  0.99],
       [ 0.49,  0.69,  0.37,  0.15,  0.72,  0.99,  0.  ,  0.67,  0.57,
         0.47,  0.66,  0.38,  0.45,  0.41,  0.32,  0.17,  0.18],
       [ 0.85,  0.93,  0.83,  0.66,  0.68,  0.95

In [7]:
# eigenvalues from skbio's PCoA function, used for verification
pcoa(B).eigvals

NameError: name 'pcoa' is not defined

In [8]:
# First transformation of the distance matrix
A = -0.5*np.square(B)
A.round(2)

array([[ 0.  , -0.06, -0.07, -0.15, -0.39, -0.5 , -0.12, -0.37, -0.32,
        -0.09, -0.36, -0.04, -0.02, -0.06, -0.22, -0.13, -0.08],
       [-0.06,  0.  , -0.1 , -0.24, -0.44, -0.5 , -0.24, -0.43, -0.4 ,
        -0.07, -0.43, -0.1 , -0.06, -0.07, -0.32, -0.23, -0.2 ],
       [-0.07, -0.1 ,  0.  , -0.07, -0.37, -0.49, -0.07, -0.34, -0.29,
        -0.02, -0.34, -0.05, -0.03, -0.01, -0.16, -0.07, -0.04],
       [-0.15, -0.24, -0.07,  0.  , -0.26, -0.49, -0.01, -0.22, -0.19,
        -0.11, -0.22, -0.09, -0.11, -0.09, -0.03, -0.02, -0.03],
       [-0.39, -0.44, -0.37, -0.26,  0.  , -0.44, -0.26, -0.23, -0.06,
        -0.4 , -0.09, -0.37, -0.39, -0.38, -0.17, -0.3 , -0.29],
       [-0.5 , -0.5 , -0.49, -0.49, -0.44,  0.  , -0.49, -0.45, -0.46,
        -0.5 , -0.45, -0.49, -0.5 , -0.5 , -0.48, -0.49, -0.49],
       [-0.12, -0.24, -0.07, -0.01, -0.26, -0.49,  0.  , -0.22, -0.16,
        -0.11, -0.22, -0.07, -0.1 , -0.08, -0.05, -0.01, -0.02],
       [-0.37, -0.43, -0.34, -0.22, -0.23, -0.45

In [9]:
# computing the mean row vector and column vector
A_col = A.mean(0)
A_row = A.mean(1)
print(A_col)
print(A_row)

[[-0.17654585 -0.22878369 -0.14834849 -0.13762148 -0.28493313 -0.45368032
  -0.13167633 -0.26978538 -0.22710801 -0.16901388 -0.25296147 -0.15571474
  -0.1629007  -0.15437161 -0.16286702 -0.1398685  -0.13048544]]
[[-0.17654585]
 [-0.22878369]
 [-0.14834849]
 [-0.13762148]
 [-0.28493313]
 [-0.45368032]
 [-0.13167633]
 [-0.26978538]
 [-0.22710801]
 [-0.16901388]
 [-0.25296147]
 [-0.15571474]
 [-0.1629007 ]
 [-0.15437161]
 [-0.16286702]
 [-0.1398685 ]
 [-0.13048544]]


In [10]:
# compute the mean of the entire matrix A
A_mean = A.mean()
A_mean

-0.19921564972810712

In [11]:
# Second transformation of the distance matrix (standardization)
E = A - A_col - A_row + A_mean
E

matrix([[  1.53876056e-01,   1.43660714e-01,   5.28179610e-02,
          -3.90565935e-02,  -1.27215475e-01,  -6.48024765e-02,
          -1.34860054e-02,  -1.17927624e-01,  -1.15158388e-01,
           5.60747086e-02,  -1.31675283e-01,   8.92424359e-02,
           1.18744205e-01,   6.67661409e-02,  -8.11405343e-02,
          -1.45654760e-02,   2.38456345e-02],
        [  1.43660714e-01,   2.58351729e-01,   8.22592240e-02,
          -7.14917178e-02,  -1.29305789e-01,  -1.47469660e-02,
          -7.38245005e-02,  -1.30977499e-01,  -1.47351875e-01,
           1.29550618e-01,  -1.46073570e-01,   8.83894142e-02,
           1.35258272e-01,   1.09522564e-01,  -1.28385484e-01,
          -6.53064117e-02,  -3.95287223e-02],
        [  5.28179610e-02,   8.22592240e-02,   9.74813320e-02,
           1.79457924e-02,  -1.36447120e-01,  -9.21701495e-02,
           1.39153672e-02,  -1.23838168e-01,  -1.15813340e-01,
           1.00486610e-01,  -1.37191664e-01,   5.24593140e-02,
           7.98153423e-02,

In [12]:
#Find the eigenvectors and eigenvalues of E.
eig_vals, eig_vecs = np.linalg.eig(E)

print('Eigenvectors \n%s' %eig_vecs.round(2))
print('\nEigenvalues \n%s' %eig_vals.round(2))

Eigenvectors 
[[-0.22 -0.08 -0.21 -0.1  -0.59  0.    0.27  0.14 -0.25  0.02 -0.4   0.24
   0.33 -0.19 -0.12 -0.11 -0.06]
 [-0.27 -0.24 -0.44 -0.21  0.09  0.24 -0.13 -0.37  0.46 -0.11  0.03  0.24
  -0.07  0.04 -0.14 -0.08 -0.31]
 [-0.22  0.02  0.03  0.07  0.3  -0.1   0.11  0.08 -0.16 -0.02  0.09  0.24
   0.2   0.48 -0.01 -0.67  0.1 ]
 [-0.02  0.2   0.28  0.1   0.1   0.18 -0.01 -0.31  0.11 -0.35 -0.52  0.24
  -0.05 -0.13  0.47 -0.07  0.15]
 [ 0.39  0.01 -0.37  0.44  0.05  0.42  0.06  0.21  0.18  0.1  -0.03  0.24
   0.04 -0.01 -0.14  0.    0.41]
 [ 0.23 -0.85  0.38  0.12 -0.04 -0.06  0.   -0.02 -0.01 -0.01  0.01  0.24
   0.   -0.    0.02 -0.   -0.05]
 [-0.03  0.2   0.24  0.11 -0.11 -0.12 -0.03 -0.03  0.23 -0.48  0.42  0.24
   0.49 -0.14 -0.24  0.16  0.05]
 [ 0.33  0.06  0.1  -0.79  0.07  0.16 -0.01  0.29 -0.01 -0.16 -0.02  0.24
  -0.11  0.04 -0.1  -0.02  0.18]
 [ 0.34  0.13 -0.26  0.2  -0.05 -0.4  -0.05 -0.02 -0.25 -0.41 -0.1   0.24
  -0.41  0.09 -0.19 -0.03 -0.3 ]
 [-0.24 -0.05 -0.07  0.

In [13]:
# Scales the eigenvactors such that their lengths are equal to their 
# corresponding eigenvalues
eig_vecs_scaled = []
for i in range(len(eig_vals)):
    eig_vec = eig_vecs[:,i]
    eig_vecs_scaled.append(eig_vec*eig_vals[i])
eig_vecs_scaled

[matrix([[-0.36697956],
         [-0.43968764],
         [-0.35272564],
         [-0.03323911],
         [ 0.63983892],
         [ 0.38196854],
         [-0.04484071],
         [ 0.53685014],
         [ 0.55313421],
         [-0.39531945],
         [ 0.63830782],
         [-0.32537455],
         [-0.4035929 ],
         [-0.38568889],
         [ 0.22056417],
         [-0.07435374],
         [-0.14886161]]), matrix([[-0.05998433],
         [-0.18764981],
         [ 0.01811067],
         [ 0.15538013],
         [ 0.00431359],
         [-0.66151293],
         [ 0.15524204],
         [ 0.04764037],
         [ 0.09890677],
         [-0.03761059],
         [ 0.06516439],
         [ 0.00924711],
         [-0.03927338],
         [-0.009757  ],
         [ 0.17763113],
         [ 0.14362669],
         [ 0.12052515]]), matrix([[-0.07661251],
         [-0.16402232],
         [ 0.01233756],
         [ 0.10499442],
         [-0.13902764],
         [ 0.14280805],
         [ 0.08881752],
         [ 0.0

In [14]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs_scaled[i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0].round(2))
    print(i[1].round(2))

Eigenvalues in descending order:
1.63
[[-0.37]
 [-0.44]
 [-0.35]
 [-0.03]
 [ 0.64]
 [ 0.38]
 [-0.04]
 [ 0.54]
 [ 0.55]
 [-0.4 ]
 [ 0.64]
 [-0.33]
 [-0.4 ]
 [-0.39]
 [ 0.22]
 [-0.07]
 [-0.15]]
0.78
[[-0.06]
 [-0.19]
 [ 0.02]
 [ 0.16]
 [ 0.  ]
 [-0.66]
 [ 0.16]
 [ 0.05]
 [ 0.1 ]
 [-0.04]
 [ 0.07]
 [ 0.01]
 [-0.04]
 [-0.01]
 [ 0.18]
 [ 0.14]
 [ 0.12]]
0.37
[[-0.08]
 [-0.16]
 [ 0.01]
 [ 0.1 ]
 [-0.14]
 [ 0.14]
 [ 0.09]
 [ 0.04]
 [-0.1 ]
 [-0.03]
 [-0.09]
 [-0.01]
 [-0.04]
 [-0.01]
 [ 0.09]
 [ 0.11]
 [ 0.07]]
0.24
[[-0.02]
 [-0.05]
 [ 0.02]
 [ 0.03]
 [ 0.11]
 [ 0.03]
 [ 0.03]
 [-0.19]
 [ 0.05]
 [ 0.  ]
 [-0.04]
 [ 0.  ]
 [-0.01]
 [ 0.01]
 [ 0.02]
 [-0.  ]
 [ 0.03]]
0.13
[[-0.08]
 [ 0.01]
 [ 0.04]
 [ 0.01]
 [ 0.01]
 [-0.  ]
 [-0.01]
 [ 0.01]
 [-0.01]
 [ 0.07]
 [ 0.01]
 [-0.05]
 [-0.02]
 [ 0.04]
 [-0.01]
 [-0.  ]
 [-0.02]]
0.1
[[ 0.  ]
 [ 0.02]
 [-0.01]
 [ 0.02]
 [ 0.04]
 [-0.01]
 [-0.01]
 [ 0.02]
 [-0.04]
 [-0.01]
 [-0.04]
 [ 0.  ]
 [ 0.  ]
 [-0.01]
 [ 0.06]
 [-0.02]
 [-0.02]]
0.05
[[ 0.01]


In [15]:
#Creates a matrix containing the two dominant eigenvectors as column vectors.
V = np.hstack((eig_pairs[0][1].reshape(17,1), 
                      eig_pairs[1][1].reshape(17,1),))
#                       eig_pairs[2][1].reshape(17,1)))

print('Matrix V:\n', V.round(2))

Matrix V:
 [[-0.37 -0.06]
 [-0.44 -0.19]
 [-0.35  0.02]
 [-0.03  0.16]
 [ 0.64  0.  ]
 [ 0.38 -0.66]
 [-0.04  0.16]
 [ 0.54  0.05]
 [ 0.55  0.1 ]
 [-0.4  -0.04]
 [ 0.64  0.07]
 [-0.33  0.01]
 [-0.4  -0.04]
 [-0.39 -0.01]
 [ 0.22  0.18]
 [-0.07  0.14]
 [-0.15  0.12]]


In [16]:
#Creates a matrix containing the three dominant eigenvectors as column vectors.
V2 = np.hstack((eig_pairs[0][1].reshape(17,1), 
                      eig_pairs[1][1].reshape(17,1), 
                eig_pairs[2][1].reshape(17,1)))

print('Matrix V2:\n', V2.round(2))

Matrix V2:
 [[-0.37 -0.06 -0.08]
 [-0.44 -0.19 -0.16]
 [-0.35  0.02  0.01]
 [-0.03  0.16  0.1 ]
 [ 0.64  0.   -0.14]
 [ 0.38 -0.66  0.14]
 [-0.04  0.16  0.09]
 [ 0.54  0.05  0.04]
 [ 0.55  0.1  -0.1 ]
 [-0.4  -0.04 -0.03]
 [ 0.64  0.07 -0.09]
 [-0.33  0.01 -0.01]
 [-0.4  -0.04 -0.04]
 [-0.39 -0.01 -0.01]
 [ 0.22  0.18  0.09]
 [-0.07  0.14  0.11]
 [-0.15  0.12  0.07]]


In [17]:
#Dimensionally reduce the data matrix into 2d
D2 = D.T.dot(V)
print(D2)

[[-128.49768688   -1.71801287]
 [ -97.45799218    3.44267851]
 [-112.87718954    1.11457994]
 [-132.55777701    1.05805771]
 [-213.07686196   -1.50968487]
 [ -47.21690551   -2.27540452]
 [-130.45058868   -1.67033908]
 [-103.91863257    6.67993612]
 [-184.78655019   -1.95554442]
 [ -82.34682075   -3.69024208]
 [ -99.99789863    5.93306349]
 [ -10.03376757   -1.30134415]
 [-121.84707976   -1.10305106]
 [-203.39104553    3.52877565]
 [-127.12878023   -7.54897399]
 [ -24.04864172   -3.82477413]
 [-832.43670292  -45.75559337]
 [-317.32574351  -58.52477222]
 [-474.47415324 -104.8073265 ]
 [-327.46872393  -48.56976357]
 [-410.83800382  -61.59305408]]


In [18]:
#Dimensionally reduce the data matrix into 3d
D3 = D.T.dot(V2)
print(D3)

[[-128.49768688   -1.71801287   -9.53194719]
 [ -97.45799218    3.44267851   -3.73667047]
 [-112.87718954    1.11457994   -7.03090196]
 [-132.55777701    1.05805771   -7.30657107]
 [-213.07686196   -1.50968487  -14.60584271]
 [ -47.21690551   -2.27540452   -4.24276162]
 [-130.45058868   -1.67033908  -10.33137437]
 [-103.91863257    6.67993612   -4.28573377]
 [-184.78655019   -1.95554442  -11.71992584]
 [ -82.34682075   -3.69024208   -8.37380688]
 [ -99.99789863    5.93306349   -3.27961027]
 [ -10.03376757   -1.30134415   -1.37463017]
 [-121.84707976   -1.10305106   -7.90728984]
 [-203.39104553    3.52877565   -8.08857371]
 [-127.12878023   -7.54897399  -13.85427061]
 [ -24.04864172   -3.82477413   -3.99546955]
 [-832.43670292  -45.75559337  -83.23800131]
 [-317.32574351  -58.52477222  -64.67846418]
 [-474.47415324 -104.8073265  -104.17273467]
 [-327.46872393  -48.56976357  -55.50323534]
 [-410.83800382  -61.59305408  -76.24352339]]


In [19]:
#Plot the two dominant principal components from PCA on a 2d axis
traces = []

trace1 = go.Scatter(
    x=D2[:8,0],
    y=D2[:8,1],
    mode='markers',
    text=['FCW18b', 'FCF4', 'FCF6TC3', 'FCP16c', 'FCS17a', 'FCC6', 'FCX16C', 'FCR15b'],
#     textposition='bottom',
    hoverinfo = 'text',
    name='Freshwater Samples',
    marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))

traces.append(trace1)

trace2 = go.Scatter(
    x=D2[8:15,0],
    y=D2[8:15,1],
    mode='markers',
    text=['SCB2a_77', 'SCB14c', 'SCR11c', 'SCQ2a', 'SCD17c', 'SCQ17a', 'SCH14a'],
#     textposition='bottom',
    hoverinfo = 'text',
    name='Marine Samples',
    marker=Marker(
            size=12,
            line=Line(
                color='green',
                width=0.5),
            opacity=0.8))

traces.append(trace2)

trace3 = go.Scatter(
    x=D2[15:,0],
    y=D2[15:,1],
    mode='markers',
    text = ['45591', '66722', '148651', '145604', '66718', '55268'],
#     textposition='bottom',
    hoverinfo = 'text',
    name='Environmental References',
    marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))

traces.append(trace3)

data = Data(traces)

layout = Layout(showlegend=True,
                xaxis=dict(title='PC1',),
                yaxis=dict(title='PC2',),
                title='2D PCoA of GH Data',
                font=dict(size=16),
                margin=dict(t=50, b=50, r=50, l=0)
               )

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='2d_PCoA')

In [23]:
#Plot the three dominant principal components from PCA on a 3d axis
traces = []

trace1 = go.Scatter3d(
    x=D3[:8,0],
    y=D3[:8,1],
    z=D3[:8,2],
    mode='markers',
    text=['FCW18b', 'FCF4', 'FCF6TC3', 'FCP16c', 'FCS17a', 'FCC6', 'FCX16C', 'FCR15b'],
#     textposition='bottom',
    hoverinfo = 'text',
    name='Freshwater Samples',
    marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))

traces.append(trace1)

trace2 = go.Scatter3d(
    x=D3[8:15,0],
    y=D3[8:15,1],
    z=D3[8:15,2],
    mode='markers',
    text=['SCB2a_77', 'SCB14c', 'SCR11c', 'SCQ2a', 'SCD17c', 'SCQ17a', 'SCH14a'],
#     textposition='bottom',
    hoverinfo = 'text',
    name=' Marine Samples',
    marker=Marker(
            size=12,
            line=Line(
                color='green',
                width=0.5),
            opacity=0.8))

traces.append(trace2)

trace3 = go.Scatter3d(
    x=D3[15:,0],
    y=D3[15:,1],
    z=D3[15:,2],
    mode='markers',
    text = ['45591', '66722', '148651', '145604', '66718', '55268'],
#     textposition='bottom',
    hoverinfo = 'text',
    name='Environmental References',
    marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))

traces.append(trace3)

data = Data(traces)

layout = Layout(showlegend=True,
                scene=Scene(xaxis=XAxis(title='PC1'),
                yaxis=YAxis(title='PC2'),zaxis=ZAxis(title='PC3')),
                title='3D PCoA of GH Data',
                margin=dict(t=50, b=50, r=0, l=0, autoexpand=False)
               )

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='3d_PCoA_GH')